version: '2'
services:
    sentimentwebapp-app:
        image: sentimentwebapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sentimentwebapp-postgresql:5432/sentimentWebApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sentimentwebapp-postgresql:
        extends:
            file: postgresql.yml
            service: sentimentwebapp-postgresql
